# Ubuntu tasks file for docker

- name: Ensure apt works over https and CA certificates are available
  apt: name={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - apt-transport-https
    - ca-certificates

- name: Add docker apt key
  apt_key: 
    keyserver: p80.pool.sks-keyservers.net 
    id: '58118E89F3A912897C070ADBF76221572C52609D'

- name: Add docker repository
  apt_repository:
    repo: 'deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main'
    state: 'present'

- name: Make sure old docker version ( lxc-docker ) is removed
  apt: name=lxc-docker state=absent purge=yes

- name: Install linux-image-extra package for Ubuntu 14.04 and 15.10
  apt: name=linux-image-extra-{{ ansible_kernel }} state=installed
  when: ansible_distribution_version == '14.04' or ansible_distribution_version == '15.10'

- name: Install apparmor for Ubuntu 12.04 and 14.04
  apt: name=apparmor state=installed
  when: ansible_distribution_version == '12.04' or ansible_distribution_version == '14.04'

- name: Install latest docker version
  apt: name=docker-engine state=latest update_cache=yes cache_valid_time=3600

- name: Make sure docker service is enabled and start on boot
  service: name=docker state=started enabled=yes

- name: Install Python pip
  apt: name=python-pip state=latest

- name: Install Docker python dependencies
  pip: name={{ item }} state=latest
  with_items: 
    - virtualenv
    - docker-py

- name: Add users to the docker group
  user:
    name:   "{{ item }}"
    groups: docker
    append: yes
  with_items: "{{docker_group_members}}"
  when: docker_group_members is defined
